# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about zkp key"
  version: "1.0.0"

servers:
  - url: "/zkp"

paths:
  /pzs:
    get:
      operationId: "zkp_initial.get_pzs"
      tags:
        - "key"
      responses:
        "200":
          description: "Successfully read pzs"
  
  /puzs:
    get:
      operationId: "zkp_initial.get_Pzs"
      tags:
        - "key"
      responses:
        "200":
          description: "Successfully read pumk"