# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/data"

components:
  schemas:
    Medicaldata:
      type: "object"
      required:
        - user_id
      properties:
        user_id:
          type: "integer"
        enc_key:
          type: "string"
        cipher:
          type: "string"

paths:
  /enc:
    get:
      operationId: "medical_data.read_all"
      tags:
        - "data"
      summary: "Read the list of data"
      responses:
        "200":
          description: "Successfully read data list"
    post:
      operationId: "medical_data.add_data"
      tags:
        - data
      summary: "add new encrypted data"
      requestBody:
          description: "data to add"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "mdata"
                $ref: "#/components/schemas/Medicaldata"
      responses:
        "201":
          description: "Successfully add data"